language: python
python:
  - "3.4.3"
addons:
  postgresql: "9.3"
env:
  - DB_NAME=django_pastime_db DB_USER=django_pastime DB_PASS=qwerty123
before_install:
  - export DATABASE_URL="postgres://django_pastime:qwerty123@127.0.0.1:5432/django_pastime_db"
install:
 - pip install -r requirements.txt
before_script:
 - psql -U postgres -c 'CREATE DATABASE django_pastime_db;'
 - psql -U postgres -c "CREATE USER django_pastime WITH PASSWORD 'qwerty123';"
 - psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE django_pastime_db to django_pastime_db;"

 - python manage.py migrate
script:
 - python manage.py test
